name: Tests

on:
  push:
    branches: [ main ]
    paths: [ 'lib/**', 'tests/**', '.github/workflows/test.yml' ]
    tags: '*'
  pull_request:
    branches: [ main ]
    paths: [ 'lib/**', 'tests/**', '.github/workflows/test.yml' ]

jobs:
  build-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
    - name: Build tests
      run: dotnet build tests
    - name: Perform Tests
      run: dotnet test --no-build --verbosity normal tests
